global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - ./alertmanager/alert.rule.yml

scrape_configs:
  - job_name: consul_sd
    metrics_path: /metrics
    scheme: http
    consul_sd_configs:
      - server: consul:8500
        scheme: http
        services:
          - oncall-web-*
          - prometheus-sre-v2-custom-exporter
          - grafana

  - job_name: 'alertmanager'
    scrape_interval: 5s
    scrape_timeout: 5s
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-exporter'
    file_sd_configs:
      - files:
        - nginx-exporter/nginx-exporter.yml

  - job_name: 'prober'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8089' ]

  - job_name: 'blackbox_http'
    scrape_interval: 15s
    metrics_path: /probe
    scheme: http
    params:
      module: [ http_2xx ]
    static_configs:
      - targets: ['oncall-web-1:8080', 'oncall-web-2:8080']
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_tcp'
    scrape_interval: 15s
    metrics_path: /probe
    scheme: http
    params:
      module: [tcp_connect]
    static_configs:
      - targets: ['oncall-web-1:8080', 'oncall-web-2:8080' ]
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox_icmp'
    scrape_interval: 15s
    metrics_path: /probe
    scheme: http
    params:
      module: [icmp_connect]
    static_configs:
      - targets:
          - oncall-web-1
          - oncall-web-2
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

